"""
Build script for the sqldiff Python extension.

Source provenance
-----------------
This package lives inside the SQLite source tree at <sqlite-root>/sqldiff_python/.
The sources it uses come from the sibling tree:

  sqldiff.c        — copied at build-time from  ../../tool/
  sqlite3_stdio.h  — copied at build-time from  ../../ext/misc/
  sqlite3_stdio.c  — copied at build-time from  ../../ext/misc/ (Windows only)
  sqlite3.c/h      — the amalgamation, generated by generate_amalgamation.py
                     and committed to sqldiff/sqlite_src/.  Run that script
                     to refresh them after pulling new SQLite changes.

Version
-------
The package version is derived automatically from <sqlite-root>/VERSION so
it always matches the SQLite release it was built against.

Self-contained build
--------------------
sqlite3.c is compiled directly into the extension — no system libsqlite3
is required at build or runtime.

Regenerating the amalgamation
------------------------------
    python generate_amalgamation.py

That script produces sqldiff/sqlite_src/sqlite3.c and sqlite3.h.
On Linux/macOS it is run automatically by cibuildwheel (see pyproject.toml).
On Windows, use the committed files or run the script inside MSYS2.
"""

import os
import re
import shutil
import sys
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext as _build_ext

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_HERE        = os.path.dirname(os.path.abspath(__file__))
_SQLITE_ROOT = os.path.dirname(_HERE)               # one level up = SQLite root
_SQLITE_SRC  = os.path.join(_HERE, "sqldiff", "sqlite_src")
_AMALGAMATION = os.path.join(_SQLITE_SRC, "sqlite3.c")

# ---------------------------------------------------------------------------
# Version — read from <sqlite-root>/VERSION; fall back to sqlite3.h
# ---------------------------------------------------------------------------

def get_version():
    version_file = os.path.join(_SQLITE_ROOT, "VERSION")
    if os.path.isfile(version_file):
        with open(version_file) as f:
            return f.read().strip()
    # Fallback: parse the committed sqlite3.h
    sqlite3_h = os.path.join(_SQLITE_SRC, "sqlite3.h")
    if os.path.isfile(sqlite3_h):
        with open(sqlite3_h) as f:
            for line in f:
                m = re.match(r'#define\s+SQLITE_VERSION\s+"([^"]+)"', line)
                if m:
                    return m.group(1)
    return "0.0.0"

# ---------------------------------------------------------------------------
# Custom build_ext: refresh sqlite3_stdio.{c,h} from the source tree before
# compiling, and guard against a missing amalgamation.
# ---------------------------------------------------------------------------

class build_ext(_build_ext):
    def run(self):
        self._refresh_sources()
        if not os.path.isfile(_AMALGAMATION):
            raise RuntimeError(
                "The SQLite amalgamation is missing.\n"
                "Run  python generate_amalgamation.py  to generate it, or\n"
                "copy a pre-built sqlite3.c / sqlite3.h into:\n"
                f"  {_SQLITE_SRC}"
            )
        super().run()

    def _refresh_sources(self):
        """
        Copy source files fresh from the SQLite source tree whenever it is
        present alongside this package.  This ensures the committed copies
        in sqlite_src/ never drift from the repo.

        Files refreshed:
          sqldiff.c          ← ../../tool/sqldiff.c
          sqlite3_stdio.c/h  ← ../../ext/misc/sqlite3_stdio.{c,h}
        """
        if not os.path.isdir(_SQLITE_ROOT):
            return  # building from an sdist — use committed files

        copies = [
            (os.path.join(_SQLITE_ROOT, "tool", "sqldiff.c"),
             os.path.join(_SQLITE_SRC,  "sqldiff.c")),
            (os.path.join(_SQLITE_ROOT, "ext", "misc", "sqlite3_stdio.c"),
             os.path.join(_SQLITE_SRC,  "sqlite3_stdio.c")),
            (os.path.join(_SQLITE_ROOT, "ext", "misc", "sqlite3_stdio.h"),
             os.path.join(_SQLITE_SRC,  "sqlite3_stdio.h")),
        ]
        for src, dst in copies:
            if os.path.isfile(src):
                shutil.copy2(src, dst)

# ---------------------------------------------------------------------------
# Extension sources
# ---------------------------------------------------------------------------

sources = [
    "sqldiff/_sqldiffmodule.c",
    # Compile the SQLite amalgamation directly into the extension — no
    # system libsqlite3 needed.
    "sqldiff/sqlite_src/sqlite3.c",
]

# On Windows, sqlite3_stdio.c provides real implementations of the
# UTF-8-safe stdio wrappers declared in sqlite3_stdio.h.
# On all other platforms those wrappers are plain #define macros, so the
# .c file is not needed.
if sys.platform == "win32":
    sources.append("sqldiff/sqlite_src/sqlite3_stdio.c")

# ---------------------------------------------------------------------------
# Compiler flags
# ---------------------------------------------------------------------------

compile_args = []
define_macros = [
    ("SQLITE_OMIT_DEPRECATED",       None),
    # Required for changeset_one_table in sqldiff.c
    ("SQLITE_ENABLE_SESSION",        None),
    ("SQLITE_ENABLE_PREUPDATE_HOOK", None),
]

if sys.platform != "win32":
    compile_args += ["-std=c11", "-O2"]
    compile_args += ["-Wno-sign-compare", "-Wno-unused-but-set-variable"]
else:
    compile_args += ["/O2"]

# ---------------------------------------------------------------------------
# Extension definition
# ---------------------------------------------------------------------------

ext = Extension(
    name="sqldiff._sqldiff",
    sources=sources,
    include_dirs=[_SQLITE_SRC],
    define_macros=define_macros,
    extra_compile_args=compile_args,
)

# ---------------------------------------------------------------------------
# setup()
# ---------------------------------------------------------------------------

def get_long_description():
    readme = os.path.join(_HERE, "README.md")
    if os.path.isfile(readme):
        with open(readme, encoding="utf-8") as f:
            return f.read()
    return ""

setup(
    name="sqlite3-sqldiff",
    version=get_version(),
    description="Python bindings for the SQLite sqldiff utility",
    long_description=get_long_description(),
    long_description_content_type="text/markdown",
    packages=["sqldiff"],
    package_data={"sqldiff": ["sqlite_src/*.h", "sqlite_src/*.c"]},
    ext_modules=[ext],
    cmdclass={"build_ext": build_ext},
    python_requires=">=3.10",
)
